name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    uses: NTU-CNAD-Group3/cicd-workflows/.github/workflows/lint-ci@main

  sonarqube:
    needs: lint
    uses: NTU-CNAD-Group3/cicd-workflows/.github/workflows/sonarqube-ci@main
